// Add more kingdoms here. The page renders cards, detail panels, search data,
// lore sections, stats, and map links from these objects.
export const kingdoms = [
  {
    id: "aquiloth",
    name: "The Empire of Aquiloth",
    status: "Active",
    theme: "Ancient winter empire",
    leader: "David",
    population: "3,120,670",
    militaryPopulation: "210,000",
    region: "Zephyr",
    colors: {
      primary: "#75d8ff",
      secondary: "#f7fbff",
      dark: "#07172f",
      glow: "rgba(117, 216, 255, 0.3)",
    },
    tagline: "One of the oldest and richest empires, guarded by walls, forts, trade routes, and the north wind.",
    overview:
      "The Empire of Aquiloth has existed for over 12 centuries and is one of the oldest, richest, and most sophisticated empires. It rules the land of Zephyr in the north-west region of the continent. The empire is known for forts, outposts, large cities, trade routes, and giant walls that protect citizens from threats.",
    notes: [
      "Aquilo means the north wind in Latin, associated with winter and cold.",
      "Source note: one date says 835 for the strongest raid. This may need correction later.",
    ],
    lore: [
      "Aquiloth began as a small town called Aquiles.",
      "Aquiles was raided by bandits, so the people built thick walls for protection.",
      "The town expanded and eventually became the Empire of Aquiloth.",
      "The military was founded soon after the walls were built.",
      "The army began with chainmail and iron armor, but later adopted diamond and netherite equipment.",
      "Privates receive diamond armor during training and netherite once they rank up.",
    ],
    military: [
      { name: "Tempests", detail: "Commanders and generals", count: "about 210" },
      { name: "Inquisitors", detail: "Spies and intelligence", count: "about 3,120" },
      { name: "Squad Leaders", detail: "Field leaders", count: "about 2,100" },
      { name: "Privates", detail: "Core army", count: "about 125,000" },
      { name: "Cavalry Troops", detail: "Mounted forces", count: "about 11,250" },
      { name: "Naval Troops", detail: "Air and sea", count: "about 15,740" },
      { name: "Medics", detail: "Battlefield support", count: "about 1,210" },
      { name: "Special Forces", detail: "Elite troops", count: "about 7,320" },
      { name: "Enforcement", detail: "Police", count: "about 22,450" },
    ],
    stats: [
      ["Current Towns", "none"],
      ["Current Cities", "1"],
      ["Current Outposts/Forts", "12"],
      ["Current Castles", "4"],
      ["Military Count", "about 188,400"],
    ],
    places: [
      {
        name: "The City of Aquiles",
        type: "Capital city",
        detail:
          "Largest city of Aquiloth, the first town founded under the name of Aquiloth, and crucial to trade and civilian industries.",
      },
      {
        name: "The Fortress of Ventulus",
        type: "Fortress",
        detail:
          "Ventulus means small breeze or slight wind. Buildings include a garrison, horse stables, and a hospital.",
      },
    ],
    timeline: [
      ["829", "The City of Aquiles was started by a small group of people."],
      ["830", "The first bandits attacked the city."],
      ["835", "Residents decided to build a wall."],
      ["842", "The wall was finished."],
      ["846", "Bandit raids continued, and a small militia was formed."],
    ],
  },
  {
    id: "draconis",
    name: "The Once Great Kingdom of Draconis",
    status: "Dead",
    theme: "Dragon ruins",
    leader: "Dead king",
    population: "0 humans, 0 dragons, 0 villagers",
    militaryPopulation: "Dead",
    region: "Ruins of Prosperity",
    colors: {
      primary: "#ff5b3f",
      secondary: "#ffb45f",
      dark: "#1a0505",
      glow: "rgba(255, 91, 63, 0.28)",
    },
    tagline: "A feared dragon kingdom built over Prosperity, now ash, silence, and bad decisions.",
    overview:
      "The Kingdom of Draconis was a newer kingdom, founded about 2 centuries ago. It was built on the former City of Prosperity, originally created by villagers from the Alliance of Prosperity.",
    notes: [
      "Draconis means dragon in Latin.",
      "Lore note: humans are players in the lore. Humans are represented by armor stands.",
    ],
    lore: [
      "Villagers created the City of Prosperity.",
      "Around 1000 years later, humans tried to take shelter there during a storm, but the villagers refused them.",
      "The humans took shelter in a cave instead, and the cave was occupied by dragons.",
      "The humans allied with the dragons and attacked the City of Prosperity.",
      "Draconis became feared across the world.",
      "The kingdom later collapsed after a dragon escaped and killed everyone.",
    ],
    military: [
      { name: "Dracon", detail: "Generals", count: "dead" },
      { name: "Head Draco", detail: "Officers", count: "dead" },
      { name: "Royal Draco", detail: "Royal guard", count: "dead" },
      { name: "Dragoneer", detail: "Cavalry", count: "dead" },
      { name: "Lead Draco", detail: "Squad leaders", count: "dead" },
      { name: "Draco", detail: "Normal soldiers", count: "dead" },
    ],
    stats: [
      ["King", "dead"],
      ["Cities", "0"],
      ["Food Supply", "gone"],
      ["Military Info", "dead"],
    ],
    places: [
      {
        name: "Former City of Prosperity",
        type: "Ruined capital",
        detail: "A villager-built city that became the core of Draconis after the dragon alliance attack.",
      },
    ],
    shops: [
      "2 human-run sword shops",
      "1 human-run shield shop",
      "1 state-run sword and shield shop",
      "1 state-run armor shop",
      "1 state-run potion shop",
      "1 human-run meat shop",
      "1 human-run bread shop",
      "1 human-run cake shop",
      "1 human-run real estate shop",
    ],
  },
  {
    id: "jurassic",
    name: "The Jurassic Empire",
    status: "Discovered",
    theme: "Ancient dinosaur jungle",
    leader: "Ty",
    population: "2,967 villagers and 274 dinosaurs",
    militaryPopulation: "about 418 defensive troops and dinosaur guardians",
    region: "Jungle Region",
    colors: {
      primary: "#8acb54",
      secondary: "#d89f35",
      dark: "#17210f",
      glow: "rgba(216, 159, 53, 0.28)",
    },
    tagline:
      "The oldest known civilization in the world: hidden under jungle canopies, amber temples, and dinosaur guardians.",
    overview:
      "The Jurassic Empire is the oldest known empire in the world. It was believed to be formed hundreds of thousands of years ago, but it was only discovered 1 to 2 years ago by a villager exploring the jungle. Though new to modern politics, the empire itself has ancient cities, amber temples, dinosaur guardians, and a defensive army built to protect its secrecy.",
    notes: [
      "Aquiloth is an old public empire. The Jurassic Empire is an ancient hidden empire.",
      "Modern archive question: should the empire stay hidden, or enter the world of kingdoms?",
    ],
    lore: [
      "A secret society of villagers rules over dinosaurs in the jungle.",
      "Ancient villagers built cities beneath tree canopies, stone cliffs, vines, and ruined temples so outsiders would think the jungle was empty.",
      "Dinosaurs are respected as royal guardians, not pets. Important dinosaurs live near temples and capital districts.",
      "The empire survived by staying hidden. While other kingdoms built walls and machines, Jurassic learned to disappear into the jungle.",
      "The empire is presumed to be huge and spread across the jungle, with several settlements still not fully mapped by the archive.",
      "It is peaceful with other kingdoms for now, but its military is defensive and very serious about unwanted visitors.",
      "Now that the empire has been discovered, Emperor Ty must decide whether to trade with the outside world or keep the jungle sealed.",
    ],
    military: [
      { name: "T. Rex Commanders", detail: "Generals and commanders", count: "8" },
      { name: "Velociraptor Officers", detail: "Fast officers and tactical leaders", count: "42" },
      { name: "Triceratops Juggernauts", detail: "Heavy defensive tanks", count: "19" },
      { name: "Compsognathus Soldiers", detail: "Core jungle soldiers", count: "300+" },
      { name: "Pteranodon Scouts", detail: "Aerial scouts and messengers", count: "25" },
      { name: "Ankylosaurus Wallbreakers", detail: "Heavy breach and gate defense units", count: "12" },
      { name: "Claw Guard", detail: "Royal protectors of Emperor Ty and Jurassica", count: "12" },
    ],
    stats: [
      ["Cities", "5 known, more suspected"],
      ["Villager Population", "2,967"],
      ["Dinosaur Population", "274"],
      ["Alliances", "none official"],
      ["Wars", "none"],
      ["Castles", "1"],
      ["Outposts/Forts", "0 public forts, hidden watch posts suspected"],
      ["Currency", "amber pieces and jungle trade goods"],
      ["Discovery Status", "recently discovered, ancient records still being translated"],
    ],
    places: [
      {
        name: "The Capital of Jurassica",
        type: "Capital city",
        detail:
          "Villager population 1,674 and dino population 23. The biggest city of the empire has a bustling center with shops, food options, important dinosaurs, and 1 dinosaur padlock.",
      },
      {
        name: "The City of Defense",
        type: "Military city",
        detail:
          "A fortified jungle city built to protect the empire from invasions. It trains Triceratops Juggernauts, Velociraptor Officers, and hidden gate guards. Some details are still being discovered.",
      },
      {
        name: "Amberfall",
        type: "Mining and farming settlement",
        detail:
          "A settlement near amber deposits and layered cliffs. Amberfall supplies decoration, trade goods, temple offerings, and pieces used like currency.",
      },
      {
        name: "Raptor's Run",
        type: "Scout city",
        detail:
          "A fast-moving messenger and scout settlement built around jungle paths, rope bridges, and velociraptor training routes.",
      },
      {
        name: "Stoneclaw Temple",
        type: "Ancient royal site",
        detail:
          "A carved stone temple where Amber Scholars keep ancient records, dinosaur markings, royal ceremonies, and warnings for outsiders.",
      },
    ],
    government: [
      "Emperor: Ty",
      "Dino Council: elder villagers who manage dinosaur care and ancient laws",
      "Claw Guard: royal protectors of the capital and emperor",
      "Jungle Keepers: farmers, builders, scouts, and path-makers",
      "Amber Scholars: historians who record ancient knowledge and translate temple carvings",
    ],
    culture: [
      "Citizens wear jungle green, amber, and stone-gray colors.",
      "Amber is used for decoration, trade, temple records, and royal symbols.",
      "The empire believes the jungle itself protects them.",
      "Outsiders may be asked to pass a Trial of the Claw before entering important cities.",
      "Dinosaurs are treated as guardians and ancient partners, not random monsters.",
    ],
    diplomacy: [
      "Aquiloth may become a future trade partner if both empires respect each other's borders.",
      "G.O.L.E.M machines are considered impressive but suspiciously loud for a hidden jungle empire.",
      "Furtivo's sculk is watched carefully because hidden empires do not enjoy mysterious spreading substances.",
      "Draconis is disliked because dragons are basically fire drama pretending to be dinosaurs.",
      "For now, the empire has no official alliances and prefers careful observation.",
    ],
    weaknesses: [
      "Dinosaurs are powerful but difficult to control during panic or invasion.",
      "The empire is ancient, but some technology is behind G.O.L.E.M and Aquiloth.",
      "Hidden roads make trade difficult and slow.",
      "The empire does not fully trust outsiders.",
      "Some dinosaurs may want more freedom from villager rule.",
    ],
    timelineTitle: "Jurassic Empire Ancient Timeline",
    timeline: [
      ["Ancient Era", "First villagers discovered dinosaurs deep in the jungle and began living beside them."],
      ["Early Empire", "Hidden temples, dinosaur paddocks, and canopy cities were built under the protection of the jungle."],
      ["Expansion Era", "Jurassica became the capital, and the empire spread through hidden jungle paths."],
      ["Isolation Era", "The empire sealed itself away so other kingdoms would think the jungle was empty."],
      ["Discovery Era", "A villager explorer found signs of the empire 1 to 2 years ago."],
      ["2025", "The Jurassic Empire now decides whether to stay hidden or enter modern kingdom politics."],
    ],
  },
  {
    id: "golem",
    name: "G.O.L.E.M",
    status: "Active",
    theme: "Steampunk copper machines",
    leader: "Najera Emilio",
    population: "487,472",
    militaryPopulation: "10,000",
    region: "Copperlands",
    colors: {
      primary: "#c97b3a",
      secondary: "#f0c572",
      dark: "#1e130c",
      glow: "rgba(201, 123, 58, 0.28)",
    },
    tagline: "The Great Original League of Emilio's Monarchy, a copper empire of machines and inventions.",
    overview:
      "G.O.L.E.M is a steampunk kingdom focused on technological advancement and powerful machinery. It has existed for about 9 centuries and is one of the oldest kingdoms.",
    lore: [
      "Founded by Eric Hemsworth, an inventor from Aquiloth.",
      "Eric left Aquiloth to make something of himself.",
      "He slowly built a small castle as a workshop.",
      "He later met Fred, a carpenter looking for employment.",
      "Together, Eric and Fred built G.O.L.E.M from the ground up.",
      "G.O.L.E.M became a copper empire filled with inventions.",
      "During rising tensions with Draconis, Eric and Fred built soldier machines to defend the kingdom.",
      "This led to the creation of the first golem.",
    ],
    military: [
      { name: "Soldier Machines", detail: "Mechanical defenders", count: "classified" },
      { name: "Golems", detail: "Heavy defense inventions", count: "prototype lineage" },
    ],
    stats: [
      ["Current Factories", "0"],
      ["Current Castles", "0"],
      ["Alliances", "Kingdom of Draconis"],
      ["Wars", "0"],
    ],
    places: [
      {
        name: "Eric's Workshop Castle",
        type: "Origin site",
        detail: "The small castle workshop where G.O.L.E.M started growing into a copper empire.",
      },
    ],
  },
  {
    id: "aquifer",
    name: "Harmonization of Aquifer",
    status: "Active",
    theme: "Waterbending refugee society",
    leader: "Coopy",
    population: "285",
    militaryPopulation: "215",
    region: "Aquifer Basin",
    colors: {
      primary: "#52e8f2",
      secondary: "#63d69a",
      dark: "#071d2b",
      glow: "rgba(82, 232, 242, 0.28)",
    },
    tagline: "A peaceful water kingdom with farms, refugees, shops, restaurants, and one very concerning warden.",
    overview:
      "The Harmonization of Aquifer is a small water-themed kingdom founded after survivors fled from Draconis. It has waterbenders, farms, shops, restaurants, and a peaceful village society.",
    notes: ["Origin Note: the source says 'proto-late-European, water, to meme.' The archive refuses to explain further."],
    lore: [
      "James came from Aquiloth.",
      "He had a family and a tea shop called Lavendeller Stellar. His father was Ryan, his mother was Anya, and his daughter was Katara.",
      "Katara became the first waterbender after learning from the moon and ocean by watching the currents.",
      "She mastered waterbending at age 13.",
      "At age 16, Katara left Aquiloth with James and her mother to find people and create their own village.",
      "They found a village of villagers and lived there for 67 and a half years until Draconis attacked.",
      "Draconis killed half the population of a village of 350 people.",
      "Survivors followed 18-year-old Katara to hide.",
      "They used money from James's tea shop to build a peaceful kingdom.",
      "They built houses for 150 surviving villagers and giant city walls to protect from ground troops and war balloons.",
      "They developed shops, restaurants, grocery stores, and factories.",
      "They trained villagers, helped refugees, expanded society, and then became bankrupt.",
    ],
    military: [
      { name: "Water Benders", detail: "Elemental defenders", count: "45" },
      { name: "Soldiers", detail: "Ground defense", count: "150" },
      { name: "Engineers", detail: "Builders and machines", count: "15" },
      { name: "Generals", detail: "Command", count: "5" },
      { name: "Kamikaze Warden", detail: "Do not let him in the palace", count: "1" },
    ],
    stats: [
      ["Current Towns", "1"],
      ["Current Outposts/Forts", "0"],
      ["Current Castles", "0"],
      ["Town State", "50 farmers, 30 villagers, 1 iron golem"],
      ["Food Supply", "10 farms, 1 wheat field, 5 cow farms, 3 pig farms, 1 fat sheep"],
    ],
    places: [
      {
        name: "Bungo's Family Diner",
        type: "Restaurant",
        detail: "A family diner. Different from the hospital. Probably.",
      },
      {
        name: "Bungo's Hospital and Not Family Diner",
        type: "Hospital",
        detail: "A hospital that would like everyone to know it is not the family diner.",
      },
      {
        name: "Banko's Groceries",
        type: "Shop",
        detail: "Main grocery store for the peaceful village society.",
      },
      {
        name: "Tango's Mexican Restaurant",
        type: "Restaurant",
        detail: "Local restaurant in Aquifer.",
      },
    ],
    shops: ["Brewery", "Cow-run slaughterhouse", "A orrery", "Ore brewery"],
  },
  {
    id: "furtivo",
    name: "Kingdom of Furtivo",
    status: "Hidden",
    theme: "Sculk exile kingdom",
    leader: "Kendrick Otter",
    population: "about 210,000",
    militaryPopulation: "about 120,234",
    region: "Islands of Silence / The End",
    colors: {
      primary: "#19d0cc",
      secondary: "#7cecff",
      dark: "#030609",
      glow: "rgba(25, 208, 204, 0.26)",
    },
    tagline: "A sculk kingdom born from exile, silence, wardens, and a single precious grass block.",
    overview:
      "The Kingdom of Furtivo is a sculk-themed kingdom founded after banishment into the Islands of Silence, also known as the End. It is connected to wardens, stealth, deep dark discoveries, and spreading towns.",
    lore: [
      "The narrator was banished to the End.",
      "They brought a grass block, which became the source of natural items in Furtivo.",
      "They admired the warden more than creepers because wardens are intelligent, stealthy, and powerful.",
      "As a young miner in their 20s, the narrator searched for emeralds.",
      "They asked the king for permission to mine in the mountains, but the king refused.",
      "The narrator returned to mining and later found a dark blue mushy substance: sculk.",
      "They hid the sculk and researched it in the Cave Encyclopedia.",
      "They learned about wardens, the Deep Dark, and sculk sensors.",
      "The narrator returned to the Deep Dark and found sculk sensors.",
      "They touched the sensor, continued deeper, and heard a loud shriek.",
      "Darkness fell.",
      "The warden began emerging from the ground.",
      "The narrator tried to run, but it was too late.",
      "To be continued...",
    ],
    military: [
      { name: "Knights", detail: "Briarstone defenders", count: "18" },
      { name: "Sires", detail: "Town forces", count: "32" },
      { name: "Men at Arms", detail: "Local fighters", count: "3" },
      { name: "Armorers", detail: "Equipment makers", count: "7" },
      { name: "Soldiers", detail: "Briarstone army", count: "12" },
      { name: "Sword Keepers", detail: "Briarstone army", count: "33" },
    ],
    stats: [
      ["Current Towns", "2"],
      ["Current Cities", "none"],
      ["Current Outposts/Forts", "blank / unknown"],
      ["Current Castles", "WIP"],
      ["Wars", "Kingdom of the Fuse"],
      ["Leader Note", "Son of Sherie Otter and his dad"],
    ],
    places: [
      {
        name: "Briarstone / StoneBriar",
        type: "Town",
        detail:
          "43 villagers, 4 horses, 13 farms, and an army that is still spreading.",
      },
      {
        name: "Steelcoah",
        type: "Town",
        detail: "More details to be added by the archive.",
      },
    ],
  },
];

export const timelineEvents = [
  "The Jurassic Empire was founded.",
  "The Empire of Aquiloth was founded.",
  'The Alliance of Prosperity created a new capital called "The City of Prosperity."',
  "Eric Hemsworth left Aquiloth to make a new kingdom.",
  "The G.O.L.E.M was founded.",
  "The Battle of Villagers started.",
  "The Kingdom of Draconis was founded.",
  "The Battle of Villagers ended.",
  "Ramey Muckelberg was banished by The Kingdom of the Fuse into the Islands of Silence.",
  "Ramey discovered sculk and its properties, eventually creating a kingdom of sculk.",
  "The Kingdom of Furtivo was founded.",
  "Katara was the first waterbender to be discovered.",
  "James and Katara left Aquiloth.",
  "James and Katara worked with villagers until the Kingdom of Draconis attacked. Some survived.",
  "G.O.L.E.M received news of the incoming war and built the first golem.",
  "The Kingdom of Draconis fell after a dragon escaped and destroyed the kingdom.",
  "The Harmonization of Aquifer was founded.",
  "The Jurassic Empire was discovered.",
  "Present day: 2025.",
];

export const newsItems = [
  {
    title: "The Kingdom of Draconis is no more.",
    body: "Royal archivists confirm the once-feared dragon kingdom has collapsed after a dragon escaped and destroyed the kingdom.",
    tag: "Breaking",
  },
  {
    title: "The Jurassic Empire has been discovered.",
    body: "A villager exploring the jungle found evidence of an ancient dinosaur empire. Please do not poke the defensive dinosaurs.",
    tag: "Discovery",
  },
  {
    title: "Please stop changing other people's stuff.",
    body: "Admin-style note from the archive: if it is not yours, maybe do not rearrange reality around it.",
    tag: "Notice",
  },
];

export const messengerItems = [
  {
    from: "The Kingdom of the Fuse",
    message: "[Message partially redacted by royal moderators] Skulk kid.",
  },
  {
    from: "Kingdom of Furtivo",
    message: "[Hostile message removed by messenger ravens.]",
  },
  {
    from: "Kingdoms World Archive",
    message: "Some messages were moderated by the Kingdoms World archive.",
  },
];

export const mapRegions = [
  { id: "zephyr", name: "Zephyr", kingdomId: "aquiloth", x: 16, y: 26 },
  { id: "jungle", name: "Jungle Region", kingdomId: "jurassic", x: 66, y: 28 },
  { id: "prosperity", name: "Ruins of Prosperity", kingdomId: "draconis", x: 43, y: 46 },
  { id: "copperlands", name: "Copperlands", kingdomId: "golem", x: 72, y: 58 },
  { id: "aquifer-basin", name: "Aquifer Basin", kingdomId: "aquifer", x: 30, y: 68 },
  { id: "silence", name: "Islands of Silence / The End", kingdomId: "furtivo", x: 84, y: 18 },
];
